/* ═══════════════════════════════════════════════════
   SideQuest — data.js
   Centralised dummy data — replace with real API calls
═══════════════════════════════════════════════════ */

"use strict";

/* ── Lomba ── */
const lombaData = [
  {
    id: 1,
    cat: "teknologi",
    title: "Gemastik XVII — Pengembangan Perangkat Lunak",
    org: "Kemendikbud Ristek RI",
    deadline: "14 Mei 2026",
    daysLeft: 2,
    tags: ["Teknologi", "Nasional"],
    color: "from-primary to-purple-500",
    emoji: "🏆",
    free: true,
    prize: null,
    desc: "Kompetisi TIK mahasiswa nasional. Bidang PPL: web, mobile, desktop.",
  },
  {
    id: 2,
    cat: "bisnis",
    title: "ASEAN Business Plan Competition 2026",
    org: "ASEAN Youth Council",
    deadline: "21 Mei 2026",
    daysLeft: 9,
    tags: ["Bisnis", "ASEAN"],
    color: "from-orange-400 to-accent",
    emoji: "💼",
    free: false,
    prize: "Rp 500rb",
    desc: "Kompetisi rencana bisnis tingkat ASEAN untuk mahasiswa.",
  },
  {
    id: 3,
    cat: "sosial",
    title: "Hult Prize 2026 — Campus Round",
    org: "Hult International Business School",
    deadline: "3 Jun 2026",
    daysLeft: 22,
    tags: ["Social Impact", "Internasional"],
    color: "from-green-400 to-teal-500",
    emoji: "🌱",
    free: true,
    prize: null,
    desc: "Kompetisi startup sosial terbesar di dunia untuk mahasiswa.",
  },
  {
    id: 4,
    cat: "teknologi",
    title: "Hackathon Nasional 2026 — Smart City",
    org: "Kemenkominfo",
    deadline: "10 Jun 2026",
    daysLeft: 29,
    tags: ["Teknologi", "Hackathon"],
    color: "from-blue-500 to-primary",
    emoji: "🌆",
    free: true,
    prize: null,
    desc: "Hackathon 48 jam membangun solusi smart city inovatif.",
  },
  {
    id: 5,
    cat: "desain",
    title: "National UI/UX Design Challenge",
    org: "Tokopedia × Google DSC",
    deadline: "25 Jun 2026",
    daysLeft: 44,
    tags: ["Desain", "UI/UX"],
    color: "from-pink-400 to-purple-400",
    emoji: "🎨",
    free: true,
    prize: null,
    desc: "Desain pengalaman pengguna terbaik untuk platform e-commerce.",
  },
  {
    id: 6,
    cat: "sains",
    title: "Lomba Karya Tulis Ilmiah Nasional",
    org: "ITS Surabaya",
    deadline: "30 Jun 2026",
    daysLeft: 49,
    tags: ["Sains", "Ilmiah"],
    color: "from-cyan-500 to-blue-500",
    emoji: "🔬",
    free: false,
    prize: "Rp 200rb",
    desc: "LKTIN bidang teknologi, sains, dan inovasi untuk mahasiswa.",
  },
  {
    id: 7,
    cat: "teknologi",
    title: "Google Solution Challenge 2026",
    org: "Google Developer Student Clubs",
    deadline: "15 Jul 2026",
    daysLeft: 64,
    tags: ["Teknologi", "Global"],
    color: "from-red-400 to-orange-400",
    emoji: "⚡",
    free: true,
    prize: null,
    desc: "Bangun solusi untuk SDGs menggunakan teknologi Google.",
  },
  {
    id: 8,
    cat: "bisnis",
    title: "Startup Weekend Jakarta 2026",
    org: "Techstars × ANGIN",
    deadline: "20 Jul 2026",
    daysLeft: 69,
    tags: ["Bisnis", "Startup"],
    color: "from-yellow-400 to-orange-400",
    emoji: "🚀",
    free: false,
    prize: "Mentoring",
    desc: "54 jam dari ide ke pitch deck. Gabung komunitas startup terbaik.",
  },
];

/* ── Matchmaking candidates ── */
const matchData = [
  {
    id: 1,
    name: "Aurel Salsabila",
    uni: "ITB Bandung",
    prodi: "Sistem dan Teknologi Informasi",
    skills: ["UI/UX Design", "Figma", "User Research"],
    exp: ["Hult Prize 2025 — Juara 1", "COMPFEST Design Finalist"],
    prestasi: ["Ksatria Data", "Dokumentasi Terbaik"],
    compat: 90,
    online: true,
    avatarColor: "bg-purple-500",
  },
  {
    id: 2,
    name: "Bimo Prasetyo",
    uni: "ITS Surabaya",
    prodi: "Teknik Komputer",
    skills: ["Backend", "Node.js", "Database", "DevOps"],
    exp: ["Gemastik XVI — Juara 2", "Hackathon Smart City 2025"],
    prestasi: ["Hackaton", "Ksatria Data"],
    compat: 85,
    online: true,
    avatarColor: "bg-blue-500",
  },
  {
    id: 3,
    name: "Citra Dewi",
    uni: "Universitas Gadjah Mada",
    prodi: "Manajemen",
    skills: ["Business Dev", "Pitching", "Market Research"],
    exp: ["ASEAN BPC 2025 — Finalist", "Startup Weekend 2024"],
    prestasi: ["Best Pitch", "Dokumentasi"],
    compat: 78,
    online: false,
    avatarColor: "bg-green-500",
  },
  {
    id: 4,
    name: "Dimas Arfian",
    uni: "BINUS University",
    prodi: "Computer Science",
    skills: ["Machine Learning", "Python", "Data Science"],
    exp: ["Kaggle Competition — Top 5%", "Data Olympiad 2025"],
    prestasi: ["Ksatria Data", "Kaggle Expert"],
    compat: 72,
    online: true,
    avatarColor: "bg-orange-500",
  },
];

/* ── Current user profile ── */
const currentUser = {
  name: "Rizki Aditya",
  initials: "RA",
  prodi: "Teknik Informatika",
  uni: "Universitas Indonesia",
  bio: "Mahasiswa Teknik Informatika UI semester 6. Passionate di web development & AI. Suka ikut hackathon dan kompetisi startup. Mencari tim untuk Gemastik & ASEAN Business Plan.",
  stats: { lombaIkuti: 7, timAktif: 3, undangan: 2, matchRate: "92%" },
  skills: [
    { label: "React.js",       cls: "tag-purple" },
    { label: "Node.js",        cls: "tag-purple" },
    { label: "UI/UX",          cls: "tag-orange" },
    { label: "Python",         cls: "tag-blue"   },
    { label: "Machine Learning", cls: "tag-green" },
    { label: "TypeScript",     cls: "tag-purple" },
    { label: "Figma",          cls: "tag-pink"   },
  ],
  riwayat: [
    {
      emoji: "🏆", bg: "bg-primary-light",
      title: "Hackathon Nasional 2025",
      org: "Kemenkominfo · Tim 3 orang",
      badge: "Juara 2", badgeCls: "text-accent bg-accent-light",
    },
    {
      emoji: "🌱", bg: "bg-green-50",
      title: "Hult Prize Campus Round 2025",
      org: "Hult International · Tim 4 orang",
      badge: "Top 10", badgeCls: "text-green-700 bg-green-100",
    },
    {
      emoji: "💡", bg: "bg-blue-50",
      title: "Ksatria Data UI 2024",
      org: "BEM FTUI · Solo",
      badge: "Peserta", badgeCls: "text-blue-700 bg-blue-100",
    },
  ],
  prestasi: [
    { title: "Ksatria Data 2024", sub: "Juara 1 Kategori ML" },
    { title: "Dokumentasi Terbaik", sub: "Gemastik XVI 2024" },
    { title: "Google DSC Speaker", sub: "Web3 Workshop 2025" },
  ],
  deadlines: [
    { day: "14", month: "Mei", name: "Gemastik XVII PPL",    left: "2 hari",  urgentCls: "text-red-500",   dotCls: "bg-red-400 pulse",  bgCls: "bg-red-50",   numCls: "text-red-500"  },
    { day: "21", month: "Mei", name: "ASEAN Business Plan",  left: "9 hari",  urgentCls: "text-accent",    dotCls: "bg-accent",         bgCls: "bg-accent-light", numCls: "text-accent"  },
    { day: "3",  month: "Jun", name: "Hult Prize Campus",    left: "22 hari", urgentCls: "text-primary",   dotCls: "bg-primary",        bgCls: "bg-primary-light", numCls: "text-primary" },
  ],
};
